using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Vulpine.Core.Data.Exceptions
{

    /// <summary>
    /// Some data structors provide read-only access, either because there internal structor
    /// dose not suport write access, or because the integrity of the data stored needs to
    /// be protected. This is the exception thrown when one atempts to write to sutch structors.
    /// </summary>
    /// <remarks>Last Update: 2015-10-05</remarks>
    public class ReadOnlyExcp : DataStruckExcp
    {
        #region Class Definitions...

        /// <summary>
        /// The default message generated by a read-only exception, prior to 
        /// applying any special case formating.
        /// </summary>
        public const string MSG = "An atempt was made to write to a protected "
            + "object that has read-only access";

        /// <summary>
        /// Creates a new empty set exception. No aditional information is
        /// passed allong, because the set is already known to be empty.
        /// </summary>
        private ReadOnlyExcp() : base() { }

        #endregion /////////////////////////////////////////////////////////////////////

        #region Class Properties...

        /// <summary>
        /// Generates a custom message, indicating the nature of the 
        /// exception. Read-Only
        /// </summary>
        public override string Message
        {
            get { return MSG; }
        }

        #endregion /////////////////////////////////////////////////////////////////////

        #region Factory Methods...

        /// <summary>
        /// Construsts and throws a read-only exception. This method
        /// dose nothing else.
        /// </summary>
        public static void Throw()
        {
            //throws an empty set exception
            throw new ReadOnlyExcp();
        }

        #endregion /////////////////////////////////////////////////////////////////////
    }
}
